# Generated by Django 2.2.2 on 2019-07-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190625_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
