# Generated by Django 2.2.2 on 2019-07-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indian', '0002_words'),
    ]

    operations = [
        migrations.DeleteModel(
            name='India',
        ),
    ]
